#!/bin/sh /etc/rc.common
#meshenger startup script

START=101
#STOP=15

start() {
    echo 'starting Meshenger'
    /usr/bin/python /root/meshenger/main.py &
}

stop() {
    echo 'Killing Meshenger'
    killall python
}
