#!/bin/sh /etc/rc.common
#meshenger startup script

START=10
STOP=15

start() {
    echo 'starting Meshenger'
    python ~/meshenger/main.py &
}

stop() {
    echo 'Killing Meshenger'
    killall python
}

